export const planets = [
  {
    id: 1,
    name: "Xokras III",
    nickname: "Plant Planet",
    description: "Habitability: 100% ",
    image_url: "https://i.imgur.com/OyRSxN3.png",
  },
  {
    id: 2,
    name: "Belepip",
    nickname: "Lava Planet",
    description: "Habitability: 0%",
    image_url: "https://i.imgur.com/5yOEUEU.png",
  },
  {
    id: 3,
    name: "Mileuth",
    nickname: "Water Planet",
    description: "Habitability: 30%",
    image_url: "https://i.imgur.com/e0Y0Un1.png",
  },
  {
    id: 4,
    name: "Biqua",
    nickname: "Ice Planet",
    description: "Habitability: 55%",
    image_url: "https://i.imgur.com/hu6CGdD.png",
  },
  {
    id: 5,
    name: "Metaro IV",
    nickname: "Venom Planet",
    description: "Habitability: 24%",
    image_url: "https://i.imgur.com/TvAyiUU.png",
  },
  {
    id: 6,
    name: "Ulelup",
    nickname: "Air Planet",
    description: "Habitability: 90%",
    image_url: "https://i.imgur.com/XsFut8y.png",
  },
  {
    id: 7,
    name: "Zulivon",
    nickname: "Sand Planet",
    description: "Habitability: 34%",
    image_url: "https://i.imgur.com/MTBGDHd.png",
  },
  {
    id: 8,
    name: "Quimacor",
    nickname: "Gold Planet",
    description: "Habitability: 47%",
    image_url: "https://i.imgur.com/q7wCUeg.png",
  },
  {
    id: 9,
    name: "Pruve",
    nickname: "Snow Planet",
    description: "Habitability: 50%",
    image_url: "https://i.imgur.com/5jlNIYO.png",
  },
  {
    id: 10,
    name: "Apicor",
    nickname: "Dark Planet",
    description: "Habitability: 82%",
    image_url: "https://i.imgur.com/kB0OsX2.png",
  },
];
